# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='DataSource Name')),
                ('type', models.CharField(choices=[('MySQL', 'MySQL'), ('SQLite', 'SQLite3'), ('Oracle', 'Oracle'), ('MSSQL', 'MicroSoft SQLServer')], default='MySQL', max_length=32, verbose_name='DataSource Type')),
                ('host', models.CharField(default='127.0.0.1', max_length=128, verbose_name='Host IP')),
                ('port', models.IntegerField(default=3306, verbose_name='DataBase Port')),
                ('db_name', models.CharField(max_length=128, verbose_name='DataBase Name')),
                ('username', models.CharField(default='root', max_length=128, verbose_name='DataBase Username')),
                ('password', models.CharField(max_length=128, verbose_name='DataBase Password')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
