# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160510_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title Of Slice'),
        ),
        migrations.AddField(
            model_name='slice',
            name='params',
            field=jsonfield2.fields.JSONField(blank=True, null=True, verbose_name='Slice Parameters'),
        ),
        migrations.AddField(
            model_name='slice',
            name='type',
            field=models.CharField(choices=[(b'Table', '\u8868\u683c'), (b'Line', 'Line'), (b'Bar', 'Bar'), (b'Map', 'Map'), (b'Pie', 'Pie'), (b'Radar', 'Radar')], default=b'Line', max_length=64, verbose_name='Slice Type'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[(b'Date', 'Date'), (b'Text', 'Text'), (b'Select', '\u9009\u62e9'), (b'Month', 'Month'), (b'SRCSelect', 'Select from a source'), (b'HLDSelect', 'Select from a source')], max_length=64, verbose_name='Filter Type'),
        ),
    ]
