# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160518_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slice',
            old_name='type',
            new_name='slice_type',
        ),
    ]
