# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160518_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sql',
            name='value',
            field=models.TextField(default=b'Null', max_length=2048, verbose_name='SQL statements'),
        ),
    ]
