# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_sql_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='params',
            field=models.TextField(blank=True, null=True, verbose_name='Slice Parameters'),
        ),
    ]
