# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 18:28
from __future__ import unicode_literals

from django.db import migrations
import jsonfield2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_slice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='params',
            field=jsonfield2.fields.JSONField(blank=True, null=True, verbose_name='Slice Parameters'),
        ),
    ]
