# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160520_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='filters',
        ),
        migrations.AddField(
            model_name='sql',
            name='filters',
            field=models.ManyToManyField(to='reports.Filter'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='slice_type',
            field=models.CharField(choices=[(b'Table', '\u8868\u683c'), (b'Line', 'Line'), (b'Bar', 'Bar'), (b'Map', 'Map'), (b'Pie', 'Pie'), (b'Radar', 'Radar'), (b'Custom', 'Custom Slice')], default=b'Line', max_length=64, verbose_name='Slice Type'),
        ),
    ]
