# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20160523_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u6570\u636e\u6e90\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[(b'MySQL', b'MySQL'), (b'SQLite', b'SQLite3'), (b'Oracle', b'Oracle'), (b'MSSQL', b'MicroSoft SQLServer')], default=b'MySQL', max_length=32, verbose_name='\u6570\u636e\u6e90\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[(b'Date', 'Date'), (b'Text', 'Text'), (b'Select', '\u9009\u62e9'), (b'Month', 'Month'), (b'SRCSelect', 'Select from a source'), (b'HLDSelect', 'Select from a source')], max_length=64, verbose_name='\u8fc7\u6ee4\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='slice_type',
            field=models.CharField(default=b'Line', max_length=64, verbose_name='\u56fe\u8868\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sql',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
