# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20160524_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='params',
            field=models.TextField(verbose_name='Slice Parameters'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='slice_type',
            field=models.CharField(default=b'line', max_length=64, verbose_name='\u56fe\u8868\u7c7b\u578b'),
        ),
    ]
